default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>


development:
  <<: *default
  database: nagarik_suchana_development

test:
  <<: *default
  database: nagarik_suchana_test

production:
  primary: &primary_production
    <<: *default
    database: nagarik_suchana_production
    username: <%= ENV.fetch("NAGARIK_SUCHANA_DATABASE_USERNAME") { "nagarik_suchana" } %>
    password: <%= ENV["NAGARIK_SUCHANA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: nagarik_suchana_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: nagarik_suchana_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: nagarik_suchana_production_cable
    migrations_paths: db/cable_migrate
