default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  connect_timeout: 10
  checkout_timeout: 5
  reaping_frequency: 10

development:
  <<: *default
  database: nagarik_suchana_development

test:
  <<: *default
  database: nagarik_suchana_test

production:
  <<: *default
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 25 } %>
  prepared_statements: false
  advisory_locks: false
